export const data = [
  { word: "reusable toilet", frequency: 45 },
  { word: "air fryer", frequency: 31 },
  { word: "fort lee", frequency: 24 },
  { word: "mulch glue", frequency: 24 },
  { word: "neon lights", frequency: 24 },
  { word: "taylor swift", frequency: 22 },
  { word: "edward robinson", frequency: 16 },
  { word: "cleaning fee", frequency: 16 },
  { word: "james charles", frequency: 16 },
  { word: "passenger seat", frequency: 16 },
  // { word: "screen protector", frequency: 15 },
  // { word: "sams club", frequency: 8 },
  // { word: "gen surg", frequency: 8 },
  // { word: "blood pressure", frequency: 8 },
  // { word: "gender reveal", frequency: 8 },
  // { word: "vp shunt", frequency: 8 },
  // { word: "toxic trait", frequency: 8 },
  // { word: "eid mubarak", frequency: 7 },
  // { word: "tik tok", frequency: 7 },
];
